# Generated by Django 5.0.4 on 2024-05-19 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_system', '0001_initial'),
        ('video_system', '0002_video_movement_type_alter_video_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementcriteria',
            old_name='criteria',
            new_name='description',
        ),
        migrations.CreateModel(
            name='TrialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_trial', models.CharField(choices=[('check', 'Check'), ('x', 'X')], max_length=5)),
                ('second_trial', models.CharField(choices=[('check', 'Check'), ('x', 'X')], max_length=5)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_results', to='assessment_system.movementcriteria')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='video_system.video')),
            ],
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
