# Generated by Django 5.0.4 on 2024-05-19 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_system', '0002_rename_criteria_movementcriteria_description_and_more'),
        ('video_system', '0002_video_movement_type_alter_video_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('movement_type', models.CharField(choices=[('run', 'Run'), ('gallop', 'Gallop'), ('hop', 'Hop'), ('leap', 'Leap'), ('horizontal_jump', 'Horizontal Jump'), ('slide', 'Slide'), ('skip', 'Skip')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='trialresult',
            name='video',
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('first_trial', 'First Trial'), ('second_trial', 'Second Trial')], max_length=20)),
                ('date_conducted', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_system.video')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_system.criterion')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_system.trial')),
            ],
        ),
        migrations.DeleteModel(
            name='MovementCriteria',
        ),
        migrations.DeleteModel(
            name='TrialResult',
        ),
    ]
