# Generated by Django 5.0.4 on 2024-05-19 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_system', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(error_messages='Error on caption.', max_length=100)),
                ('video', models.FileField(error_messages='Wrong type of video.', upload_to='videos/%Y/%m/%d/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, error_messages='Error on client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='client_system.client')),
            ],
        ),
    ]
