# Generated by Django 5.0.4 on 2024-05-19 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_system', '0001_initial'),
        ('video_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='movement_type',
            field=models.CharField(choices=[('run', 'Run'), ('gallop', 'Gallop'), ('hop', 'Hop'), ('leap', 'Leap'), ('horizontal_jump', 'Horizontal Jump'), ('slide', 'Slide'), ('skip', 'Skip')], default='run', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='client_system.client'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d'),
        ),
    ]
